### PR TITLE
Upgrade to Python 3

### PR DESCRIPTION
**Pull request by markbreedlove**
This PR makes various changes to make the module compatible with Python 3 and Django 2.2.

### CODE REVIEW

**Comment by blarghmatey** [comment]
This all seems good. We should probably also update setup.py to change the version number, add some trove classifiers to signify that this supports Python 3, and update the requirements in setup.py to depend on Django 2.

**Comment by markbreedlove** [comment]
Will do.

I also neglected to update `tests.py`, so I'll do that and make sure the tests are OK.

**Comment by blarghmatey** [comment]
:+1:

**Comment by markbreedlove** [comment]
I've updated `setup.py`. I incremented the version, which is not very meaningful because of the way the project was forked 4 times, preserving the version number, but internally, for our purposes, the version number is new for Python 3 and Django 2.2.

**Comment by markbreedlove** [comment]
@blarghmatey Do you know the proper way to run the tests in `tests.py`? I tried to update them as well as I can but it's not clear to me how to run them in the context of the Django app.

**Comment by markbreedlove** [comment]
BTW, I've run `python manage.py test` from the Django app, but it says there are 0 tests. I've tried running tests.py various ways from within the module's working directory, but have not got that to work.

**Comment by blarghmatey** [comment]
Usually you would use a test runner such as pytest or the built in Unittest module.

**Comment by markbreedlove** [comment]
Tried those, got errors about the Django configuration not being set.

**Pull request merged**
